apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mediawiki
  name: tw-mediawiki
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mediawiki
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - image: avinash2090/mediawiki
        name: tw-mediawiki
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
        volumeMounts:
        - mountPath: "/var/www/mediawiki/images"
          name: wiki-pv
        - mountPath: "/var/www/mediawiki/LocalSettings.php"
          name: php-setting
          subPath: "LocalSettings.php"
      volumes:
      - name: wiki-pv
        hostPath:
         path: /mnt/wiki_images
         type: DirectoryOrCreate
      - name: php-setting
        configMap:
          defaultMode: 420
          name: phpsetting
      dnsPolicy: ClusterFirst
      restartPolicy: Always
