apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediawiki
  name: tw-mediawiki-svc
  namespace: default
spec:
  selector:
    app: mediawiki
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32191
  type: NodePort
